In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Submited version.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Submited version.csv'

In [23]:
df

,Economies,Year,ID,Institutions,Human capital and research,Infrastructure,Market sophistication,Business sophistication,Knowledge and technology outputs,Creative outputs,Global Innovation Index,GNI per capita in current U.S. dollars,Income level (GNI Thresholds),"GDP per capita, ppp (constant 2017 international $)",GDP per capita ppp (current international $)
0,Albania,2011,2,65.2,32.7,26.4,47.5,19.6,18.0,27.3,30.45,4410.0,3.0,11052.793610,10207.767570
1,Albania,2012,2,55.0,26.2,33.6,49.7,22.6,18.5,28.1,30.40,4360.0,3.0,11227.966330,10526.259180
2,Albania,2013,2,58.9,27.1,31.1,56.8,21.4,19.2,26.1,30.90,4540.0,3.0,11361.268600,10570.963730
3,Albania,2014,2,58.8,22.8,34.1,61.9,24.9,20.2,20.6,30.50,4540.0,3.0,11586.833880,11259.267510
4,Albania,2015,2,60.1,21.8,39.0,59.1,26.2,18.5,22.0,30.70,4390.0,3.0,11878.454450,11658.905520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,Zimbabwe,2018,230,36.4,27.0,20.3,41.3,19.6,19.3,15.4,23.10,1350.0,2.0,2497.136618,2556.793484
1784,Zimbabwe,2019,230,37.6,27.8,21.7,38.4,20.6,17.5,13.3,22.30,1210.0,2.0,2310.634802,2408.154197
1785,Zimbabwe,2020,230,40.3,20.9,16.4,44.1,18.2,12.9,11.0,20.00,1140.0,2.0,2134.555461,2251.455674
1786,Zimbabwe,2021,230,40.7,24.6,19.8,46.7,18.7,11.7,15.7,21.90,1400.0,2.0,2225.094972,2444.478237
1787,Zimbabwe,2022,230,33.3,21.6,23.6,18.5,22.5,12.3,12.3,18.10,NaN,NaN,NaN,NaN

In [24]:
df[df.isna().sum(axis = 1) != 0]

,Economies,Year,ID,Institutions,Human capital and research,Infrastructure,Market sophistication,Business sophistication,Knowledge and technology outputs,Creative outputs,Global Innovation Index,GNI per capita in current U.S. dollars,Income level (GNI Thresholds),"GDP per capita, ppp (constant 2017 international $)",GDP per capita ppp (current international $)
11,Albania,2022,2,51.4,22.7,46.3,25.4,30.4,12.6,14.6,24.4,NaN,NaN,NaN,NaN
23,Algeria,2022,3,47.2,26.1,31.1,12.1,16.8,7.7,5.7,16.7,NaN,NaN,NaN,NaN
24,Angola,2011,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3370.0,2.0,7676.607496,6710.750725
29,Angola,2016,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2480.0,2.0,7569.209398,7103.226249
30,Angola,2017,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,2.0,7310.896551,7310.896551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1762,Yemen,2021,228,27.6,10.1,19.8,29.0,18.6,7.2,12.2,15.4,NaN,NaN,NaN,NaN
1763,Yemen,2022,228,17.5,11.3,25.3,26.2,15.7,6.2,10.4,13.8,NaN,NaN,NaN,NaN
1775,Zambia,2022,229,37.5,14.8,26.7,22.0,21.3,8.6,5.7,15.8,NaN,NaN,NaN,NaN
1781,Zimbabwe,2016,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1390.0,2.0,2341.304920,2806.469032
1787,Zimbabwe,2022,230,33.3,21.6,23.6,18.5,22.5,12.3,12.3,18.1,NaN,NaN,NaN,NaN

In [28]:
df_clean = df.dropna()

In [29]:
df_clean

,Economies,Year,ID,Institutions,Human capital and research,Infrastructure,Market sophistication,Business sophistication,Knowledge and technology outputs,Creative outputs,Global Innovation Index,GNI per capita in current U.S. dollars,Income level (GNI Thresholds),"GDP per capita, ppp (constant 2017 international $)",GDP per capita ppp (current international $)
0,Albania,2011,2,65.2,32.7,26.4,47.5,19.6,18.0,27.3,30.45,4410.0,3.0,11052.793610,10207.767570
1,Albania,2012,2,55.0,26.2,33.6,49.7,22.6,18.5,28.1,30.40,4360.0,3.0,11227.966330,10526.259180
2,Albania,2013,2,58.9,27.1,31.1,56.8,21.4,19.2,26.1,30.90,4540.0,3.0,11361.268600,10570.963730
3,Albania,2014,2,58.8,22.8,34.1,61.9,24.9,20.2,20.6,30.50,4540.0,3.0,11586.833880,11259.267510
4,Albania,2015,2,60.1,21.8,39.0,59.1,26.2,18.5,22.0,30.70,4390.0,3.0,11878.454450,11658.905520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1782,Zimbabwe,2017,230,35.7,28.7,15.5,37.2,22.8,14.0,17.2,21.80,1350.0,2.0,2416.049969,2416.049969
1783,Zimbabwe,2018,230,36.4,27.0,20.3,41.3,19.6,19.3,15.4,23.10,1350.0,2.0,2497.136618,2556.793484
1784,Zimbabwe,2019,230,37.6,27.8,21.7,38.4,20.6,17.5,13.3,22.30,1210.0,2.0,2310.634802,2408.154197
1785,Zimbabwe,2020,230,40.3,20.9,16.4,44.1,18.2,12.9,11.0,20.00,1140.0,2.0,2134.555461,2251.455674
1786,Zimbabwe,2021,230,40.7,24.6,19.8,46.7,18.7,11.7,15.7,21.90,1400.0,2.0,2225.094972,2444.478237

In [30]:
df_clean.to_csv("cleaned_data.csv", index = False)

In [6]:
df_clean = pd.read_csv('/Users/kylexiao/Desktop/MIE1624H/final project/cleaned_data.csv')

In [7]:
df_clean = df_clean.drop(columns=['Economies','Year','ID'])

In [11]:
target = df_clean['Global Innovation Index']
df_clean = df_clean.drop(columns=['Global Innovation Index'])

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df_clean, target, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse:.4f}")

# Get feature importance (coefficients)
feature_importance = pd.DataFrame({
    'Feature': df_clean.columns,
    'Coefficient': model.coef_
}).sort_values(by='Coefficient', ascending=False)

print("Feature Importance:")
print(feature_importance)

Mean Squared Error: 0.0011
Feature Importance:
                                              Feature   Coefficient
5                    Knowledge and technology outputs  2.501038e-01
6                                    Creative outputs  2.497186e-01
4                             Business sophistication  1.001427e-01
0                                        Institutions  9.991839e-02
3                               Market sophistication  9.983966e-02
1                          Human capital and research  9.980279e-02
2                                      Infrastructure  9.954935e-02
9   GDP per capita, ppp (constant 2017 internation...  1.377560e-06
7             GNI per capita in current U.S. dollars   7.070466e-07
10       GDP per capita ppp (current international $) -1.414954e-06
8                       Income level (GNI Thresholds) -1.036347e-03